export const arr = [
  {
    id: '1',
    name: 'Al-Fatiah',
    type: 'Madani',
    Verses: '7',
    arabic: 'الفاتحة',
  },
  {
    id: '2',
    name: 'Al-Baqarah',
    type: 'Madani',
    Verses: '286',
    arabic: ' البقرة',
  },
  {
    id: '3',
    name: 'Al-Imran',
    type: 'Madani',
    Verses: '200',
    arabic: 'آل عمران',
  },
  {
    id: '4',
    name: 'An-NIsa',
    type: 'Madani',
    Verses: '176',
    arabic: 'ٱلنساء',
  },
  {
    id: '5',
    name: "Al-Ma'idah",
    type: 'Madani',
    Verses: '120',
    arabic: ' ٱلْمَائِدَة',
  },
  {
    id: '6',
    name: "Al-An'am",
    type: 'Madani',
    Verses: '165',
    arabic: ' ٱلأنعام',
  },
  {
    id: '7',
    name: "Al-A'raf",
    type: 'Madani',
    Verses: '206',
    arabic: 'ٱلْأَعْرَاف',
  },
  {
    id: '8',
    name: 'Al-Anfal',
    type: 'Madani',
    Verses: '206',
    arabic: 'ٱلْأَنْفَال',
  },
  {
    id: '9',
    name: 'At-Tawbah',
    type: 'Madani',
    Verses: '129',
    arabic: 'ٱلتَّوْبَة',
  },
  {
    id: '10',
    name: 'Yunus',
    type: 'Makkai',
    Verses: '109',
    arabic: '	يُونُس',
  },
  {
    id: '11',
    name: 'Hud',
    type: 'Makkai',
    Verses: '123',
    arabic: '	هُود',
  },
  {
    id: '12',
    name: 'Yusuf',
    type: 'Makkai',
    Verses: '111',
    arabic: '		يُوسُف',
  },
  {
    id: '13',
    name: "Ar-Ra'd",
    type: 'Madani',
    Verses: '43',
    arabic: '	ٱلرَّعْد',
  },
  {
    id: '14',
    name: 'Ibrahim',
    type: 'Makkai',
    Verses: '52',
    arabic: 'إِبْرَاهِيم',
  },
  {
    id: '15',
    name: 'Al-Hijr',
    type: 'Makkai',
    Verses: '99',
    arabic: 'ٱلْحِجْر',
  },
  {
    id: '16',
    name: 'An-Nahl',
    type: 'Makkai',
    Verses: '128',
    arabic: 'ٱلنَّحْل',
  },
  {
    id: '17',
    name: 'Al-Isra',
    type: 'Makkai',
    Verses: '111',
    arabic: 'ٱلْإِسْرَاء',
  },
  {
    id: '18',
    name: 'Al-Kahf',
    type: 'Makkai',
    Verses: '110',
    arabic: 'ٱلْكَهْف',
  },
  {
    id: '19',
    name: 'Maryam',
    type: 'Makkai',
    Verses: '98',
    arabic: 'مَرْيَم',
  },
  {
    id: '20',
    name: 'Ta-Ha',
    type: 'Makkai',
    Verses: '135',
    arabic: 'طه',
  },
  {
    id: '21',
    name: 'Al-Anbiya',
    type: 'Makkai',
    Verses: '112',
    arabic: 'ٱلْأَنْبِيَاء',
  },
  {
    id: '22',
    name: 'Al-Hajj',
    type: 'Madani',
    Verses: '78',
    arabic: 'ٱلْحَجّ',
  },
  {
    id: '23',
    name: "Al-Mu'minun",
    type: 'Makkai',
    Verses: '118 ',
    arabic: 'ٱلْمُؤْمِنُون',
  },
  {
    id: '24',
    name: 'An-Nur',
    type: 'Madani',
    Verses: '64',
    arabic: 'ٱلنُّور',
  },

  {
    id: '25',
    name: 'Al-Furqan',
    type: 'Makkai',
    Verses: '77',
    arabic: 'ٱلْفُرْقَان',
  },
  {
    id: '26',
    name: "Ash-Shu'ara",
    type: 'Makkai',
    Verses: '227',
    arabic: 'ٱلشُّعَرَاء',
  },
  {
    id: '27',
    name: 'An-Naml',
    type: 'Makkai',
    Verses: '93',
    arabic: 'ٱلنَّمْل',
  },
  {
    id: '28',
    name: 'Al-Qasas',
    type: 'Makkai',
    Verses: '88',
    arabic: 'ٱلْقَصَص',
  },
  {
    id: '29',
    name: 'Al-Ankabut',
    type: 'Makkai',
    Verses: '69',
    arabic: 'ٱلْعَنْكَبُوت',
  },
  {
    id: '30',
    name: 'Ar-Rum',
    type: 'Makkai',
    Verses: '60',
    arabic: 'ٱلرُّوم',
  },
  {
    id: '31',
    name: 'Luqmaan',
    type: 'Makkai',
    Verses: '34',
    arabic: 'لُقْمَان',
  },
  {
    id: '32',
    name: 'As-Sajdah',
    type: 'Makkai',
    Verses: '30',
    arabic: 'ٱلسَّجْدَة',
  },
  {
    id: '33',
    name: 'Al-Ahzaab',
    type: 'Madani',
    Verses: '73',
    arabic: 'ٱلْأَحْزَاب',
  },
  {
    id: '34',
    name: 'Saba',
    type: 'Makkai',
    Verses: '54',
    arabic: 'سَبَأ',
  },
  {
    id: '35',
    name: 'Faatir',
    type: 'Makkai',
    Verses: '45',
    arabic: 'فَاطِر',
  },
  {
    id: '36',
    name: 'Ya-Sin',
    type: 'Makkai',
    Verses: '1832',
    arabic: '	يس',
  },
  {
    id: '37',
    name: 'As-Saaffaat',
    type: 'Makkai',
    Verses: '182',
    arabic: 'ٱلصَّافَّات',
  },
  {
    id: '38',
    name: '	Saad',
    type: 'Makkai',
    Verses: '88',
    arabic: 'ص',
  },
  {
    id: '39',
    name: 'Az-Zumar',
    type: 'Makkai',
    Verses: '75',
    arabic: 'ٱلزُّمَر',
  },
  {
    id: '40',
    name: 'Ghafir',
    type: 'Makkai',
    Verses: '85',
    arabic: 'غَافِر',
  },
  {
    id: '41',
    name: 'Fussilat',
    type: 'Makkai',
    Verses: '54',
    arabic: 'فُصِّلَت',
  },
  {
    id: '42',
    name: 'Ash-Shura',
    type: 'Makkai',
    Verses: '53',
    arabic: 'ٱلشُّورىٰ',
  },
  {
    id: '43',
    name: 'Az-Zhukhruf',
    type: 'Makkai',
    Verses: '89',
    arabic: 'ٱلْزُّخْرُف',
  },
  {
    id: '44',
    name: 'Ad-Dukhaan',
    type: 'Makkai',
    Verses: '59',
    arabic: 'ٱلدُّخَان',
  },
  {
    id: '45',
    name: 'Al-Jaathiyah',
    type: 'Makkai',
    Verses: '37',
    arabic: 'ٱلْجَاثِيَة',
  },
  {
    id: '46',
    name: 'Al-Ahqaaf',
    type: 'Makkai',
    Verses: '35',
    arabic: 'ٱلْأَحْقَاف',
  },
  {
    id: '47',
    name: 'Muhammad',
    type: 'Madani',
    Verses: '38',
    arabic: 'مُحَمَّد',
  },
  {
    id: '48',
    name: 'Al-Fath',
    type: 'Madani',
    Verses: '29',
    arabic: 'ٱلْفَتْح',
  },
  {
    id: '49',
    name: 'Al-Hujuraat',
    type: 'Madani',
    Verses: '18',
    arabic: 'ٱلْحُجُرَات',
  },
  {
    id: '50',
    name: '	Qaaf',
    type: 'Makki',
    Verses: '45',
    arabic: 'ق',
  },
  {
    id: '51',
    name: 'Adh-Dhaariyaat',
    type: 'Makkai',
    Verses: '60',
    arabic: 'ٱلذَّارِيَات',
  },
  {
    id: '52',
    name: 'At-Toor',
    type: 'Makkai',
    Verses: '49',
    arabic: 'ٱلطُّور',
  },
  {
    id: '53',
    name: 'An-Najm',
    type: 'Makkai',
    Verses: '62',
    arabic: 'ٱلنَّجْم',
  },
  {
    id: '54',
    name: 'Al-Qamar',
    type: 'Makkai',
    Verses: '55',
    arabic: 'ٱلْقَمَر',
  },
  {
    id: '55',
    name: 'Ar-Rahman',
    type: 'Madano',
    Verses: '78',
    arabic: 'ٱلرَّحْمَٰن',
  },
  {
    id: '56',
    name: "Al-Waqi'ah",
    type: 'Makkai',
    Verses: '96',
    arabic: 'ٱلْوَاقِعَة',
  },
  {
    id: '57',
    name: 'Al-Hadeed',
    type: 'Madani',
    Verses: '29',
    arabic: 'ٱلْحَدِيد',
  },
  {
    id: '58',
    name: 'Al-Mujadila',
    type: 'Madani',
    Verses: '22',
    arabic: 'ٱلْمُجَادِلَة',
  },
  {
    id: '59',
    name: 'Al-Hashr',
    type: 'Madani',
    Verses: '24',
    arabic: 'ٱلْحَشْر',
  },
  {
    id: '60',
    name: 'Al-Mumtahanah',
    type: 'Madani',
    Verses: '13',
    arabic: 'ٱلْمُمْتَحَنَة',
  },
  {
    id: '61',
    name: 'As-Saff',
    type: 'Madani',
    Verses: '14',
    arabic: 'ٱلصَّفّ',
  },
  {
    id: '62',
    name: "Al-Jumu'ah",
    type: 'Madani',
    Verses: '11',
    arabic: 'ٱلْجُمُعَة',
  },
  {
    id: '63',
    name: 'Al-Munafiqoon',
    type: 'Madani',
    Verses: '11',
    arabic: 'ٱلْمُنَافِقُون',
  },
  {
    id: '64',
    name: 'At-Taghabun',
    type: 'Madani',
    Verses: '18',
    arabic: 'ٱلتَّغَابُن',
  },
  {
    id: '65',
    name: 'At-Talaq',
    type: 'Madani',
    Verses: '12',
    arabic: 'ٱلطَّلَاق',
  },
  {
    id: '66',
    name: 'At-Tahreem',
    type: 'Madani',
    Verses: '12',
    arabic: 'ٱلتَّحْرِيم',
  },
  {
    id: '67',
    name: 'Al-Mulk',
    type: 'Makki',
    Verses: '30',
    arabic: 'ٱلْمُلْك',
  },
  {
    id: '68',
    name: 'Al-Qalam',
    type: 'Makki',
    Verses: '52',
    arabic: 'ٱلْقَلَم',
  },
  {
    id: '69',
    name: 'Al-Haaqqa',
    type: 'Makki',
    Verses: '52',
    arabic: 'ٱلْحَاقَّة',
  },
  {
    id: '70',
    name: "Al-Ma'aarij",
    type: 'Makki',
    Verses: '44',
    arabic: 'ٱلْمَعَارِج',
  },
  {
    id: '71',
    name: 'Nuh',
    type: 'Makki',
    Verses: '28',
    arabic: 'نُوح',
  },
  {
    id: '72',
    name: 'Al-Jinn',
    type: 'Makki',
    Verses: '28',
    arabic: 'ٱلْجِنّ',
  },
  {
    id: '73',
    name: 'Al-Muzzammil',
    type: 'Makki',
    Verses: '20',
    arabic: 'ٱلْمُزَّمِّل',
  },
  {
    id: '74',
    name: 'Al-Muddaththir',
    type: 'Makki',
    Verses: '56',
    arabic: 'ٱلْمُدَّثِّر',
  },
  {
    id: '75',
    name: 'Al-Qiyamah',
    type: 'Makki',
    Verses: '40',
    arabic: 'ٱلْقِيَامَة',
  },
  {
    id: '76',
    name: 'Al-Insaan',
    type: 'Makki',
    Verses: '31',
    arabic: 'ٱلْإِنْسَان',
  },
  {
    id: '77',
    name: 'Al-Mursalaat',
    type: 'Makki',
    Verses: '50',
    arabic: 'ٱلْمُرْسَلَات',
  },
  {
    id: '78',
    name: "An-Naba'",
    type: 'Makki',
    Verses: '40',
    arabic: 'ٱلنَّبَأ',
  },
  {
    id: '79',
    name: "An-Naazi'aat",
    type: 'Makki',
    Verses: '46',
    arabic: 'ٱلنَّازِعَات',
  },
  {
    id: '80',
    name: 'Abasa',
    type: 'Makki',
    Verses: '42',
    arabic: 'عَبَسَ',
  },
  {
    id: '81',
    name: 'At-Takweer',
    type: 'Makki',
    Verses: '29',
    arabic: 'ٱلتَّكْوِير',
  },
  {
    id: '82',
    name: 'Al-Infitar',
    type: 'Makki',
    Verses: '19',
    arabic: 'ٱلْإِنْفِطَار',
  },
  {
    id: '83',
    name: 'At-Taffeef',
    type: 'Makki',
    Verses: '36',
    arabic: 'ٱلْمُطَفِّفِين',
  },
  {
    id: '84',
    name: 'Al-Inshiqaaq',
    type: 'Makki',
    Verses: '25',
    arabic: 'ٱلْإِنْشِقَاق',
  },
  {
    id: '85',
    name: 'Al-Burooj',
    type: 'Makki',
    Verses: '22',
    arabic: 'ٱلْبُرُوج',
  },
  {
    id: '86',
    name: 'At-Taariq',
    type: 'Makki',
    Verses: '17',
    arabic: 'ٱلطَّارِق',
  },
  {
    id: '87',
    name: "Al-A'la",
    type: 'Makki',
    Verses: '19',
    arabic: 'ٱلْأَعْلَىٰ',
  },
  {
    id: '88',
    name: 'Al-Ghaashiyah',
    type: 'Makki',
    Verses: '26',
    arabic: 'ٱلْغَاشِيَة',
  },
  {
    id: '89',
    name: 'Al-Fajr',
    type: 'Makki',
    Verses: '30',
    arabic: 'ٱلْفَجْر',
  },
  {
    id: '90',
    name: 'Al-Balad',
    type: 'Makki',
    Verses: '20',
    arabic: 'ٱلْبَلَد',
  },
  {
    id: '91',
    name: 'Ash-Shams',
    type: 'Makki',
    Verses: '15',
    arabic: 'ٱلشَّمْس',
  },
  {
    id: '92',
    name: 'Al-Layl',
    type: 'Makki',
    Verses: '21',
    arabic: 'ٱللَّيْل',
  },
  {
    id: '93',
    name: 'Ad-Dhuha',
    type: 'Makki',
    Verses: '11',
    arabic: 'ٱلضُّحَىٰ',
  },
  {
    id: '94',
    name: 'Ash-Sharh',
    type: 'Makki',
    Verses: '',
    arabic: 'ٱلشَّرْح',
  },
  {
    id: '95',
    name: 'At-Tin',
    type: 'Makki',
    Verses: '8',
    arabic: 'ٱلتِّين',
  },
  {
    id: '96',
    name: 'Al-Alaq',
    type: 'Makki',
    Verses: '8',
    arabic: 'ٱلْعَلَق',
  },
  {
    id: '97',
    name: 'Al-Qadr',
    type: 'Makki',
    Verses: '19',
    arabic: 'ٱلْقَدْر',
  },
  {
    id: '98',
    name: 'Al-Bayyinahh',
    type: 'Madani',
    Verses: '5',
    arabic: 'ٱلْبَيِّنَة',
  },
  {
    id: '99',
    name: 'Az-Zalzalah',
    type: 'Madani',
    Verses: '8',
    arabic: 'ٱلزَّلْزَلَة',
  },
  {
    id: '100',
    name: "Al-'Aadiyat",
    type: 'Makki',
    Verses: '11',
    arabic: 'ٱلْعَادِيَات',
  },
  {
    id: '101',
    name: "Al-Qaari'ah",
    type: 'Makki',
    Verses: '11',
    arabic: 'ٱلْقَارِعَة',
  },
  {
    id: '102',
    name: 'At-Takaathur',
    type: 'Makki',
    Verses: '8',
    arabic: 'ٱلتَّكَاثُر',
  },
  {
    id: '103',
    name: "Al-'Asr",
    type: 'Makki',
    Verses: '3',
    arabic: '',
  },
  {
    id: '104',
    name: 'Al-Humazah',
    type: 'Makki',
    Verses: '9',
    arabic: 'ٱلْهُمَزَة',
  },
  {
    id: '105',
    name: 'Al-Feel',
    type: 'Makki',
    Verses: '5',
    arabic: 'ٱلْفِيل',
  },
  {
    id: '106',
    name: 'Quraish',
    type: 'Makki',
    Verses: '4',
    arabic: 'قُرَيْش',
  },
  {
    id: '107',
    name: "Al-Maa'oon",
    type: 'Makki',
    Verses: '7',
    arabic: 'ٱلْمَاعُون',
  },
  {
    id: '108',
    name: 'Al-Kawthar',
    type: 'Makki',
    Verses: '3',
    arabic: 'ٱلْكَوْثَر',
  },
  {
    id: '109',
    name: 'Al-Kaafiroon',
    type: 'Makki',
    Verses: '6',
    arabic: 'ٱلْكَافِرُون',
  },
  {
    id: '110',
    name: 'An-Nasr',
    type: 'Madani',
    Verses: '3',
    arabic: 'ٱلنَّصْر',
  },
  {
    id: '111',
    name: 'Al-Masad',
    type: 'Makki',
    Verses: '5',
    arabic: 'ٱلْمَسَد',
  },
  {
    id: '112',
    name: 'Al-Ikhlaas',
    type: 'Makki',
    Verses: '4',
    arabic: 'ٱلْإِخْلَاص',
  },
  {
    id: '113',
    name: 'Al-Falaq',
    type: 'Makki',
    Verses: '5',
    arabic: 'ٱلْفَلَق',
  },
  {
    id: '114',
    name: 'An-Naas',
    type: 'Makki',
    Verses: '6',
    arabic: 'ٱلنَّاس',
  },
];
export const AllSurah = [
  {
    name: 'الفاتحة',
    ayat: [
      'بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ',
      'ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ',
      'ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ',
      'مَٰلِكِ يَوۡمِ ٱلدِّينِ',
      'إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ',
      'ٱهۡدِنَا ٱلصِّرَٰطَ ٱلۡمُسۡتَقِيمَ',
      'صِرَٰطَ ٱلَّذِينَ أَنۡعَمۡتَ عَلَيۡهِمۡ غَيۡرِ ٱلۡمَغۡضُوبِ عَلَيۡهِمۡ وَلَا ٱلضَّآلِّينَ',
    ],
  },
];
